#!/usr/bin/env python
# encoding: utf-8
'''
ngnmstest.py -- run testcases for NGNMS.

ngnmstest.py - run testcases from excel file, 
read configurations tabs for HUB, VSAT,
and store result in excel file.

@author:     Vitalie Ghelbert
@copyright:  2013 Gilat Satellite Networks. All rights reserved.
@contact:    vitalieg
@deffield    updated: Updated
'''

import sys
import os

from vsat import selftest
from optparse import OptionParser

__all__ = []
__version__ = 0.1
__date__ = '2013-03-12'
__updated__ = '2013-03-12'

DEBUG = 0
TESTRUN = 0
PROFILE = 0

def main(argv=None):
    '''Command line options.'''
    
    # show help if now arguments provided.
    if len(sys.argv) == 1:
        sys.argv.append('-h')
    program_name = os.path.basename(sys.argv[0])
    program_version = "v0.1"
    program_build_date = "%s" % __updated__
 
    program_version_string = '%%prog %s (%s)' % (program_version, program_build_date)
    #program_usage = '''usage: spam two eggs''' # optional - will be autogenerated by optparse
    
    # optional - give further explanation about what the program does
    program_longdesc = "%s - read HUB, VSAT configurations and run test cases from excel file, and store results in the same excel file." % program_name 
    program_license = "Copyright 2013 Gilat"
 
    if argv is None:
        argv = sys.argv[1:]
    try:
        # setup option parser
        parser = OptionParser(version=program_version_string, epilog=program_longdesc, description=program_license)
        parser.add_option('-c', '--check', dest='testcases', type='choice', choices=['all', 'active', 'vsat'], help='''select from [all, active, vsat] testcases.''')
        parser.add_option('-i', '--in-file', dest='infile', default='data/test.xls', help='''excel file with testcases [default: data/test.xls]''')
        parser.add_option('-r', '--run-active', dest='run_active', action='store_true', default=False, help='run active testcases.')
        
        # set defaults
        # parser.set_defaults(infile="test.xls")
        
        # process options
        options, args = parser.parse_args()
            
        # ============== MAIN BODY ============= #
        '''
        Test ngnms.
        '''
        xlfile = options.infile
        
        if options.testcases == 'all':
            selftest.show_all_testcases(xlfile)
        elif options.testcases == 'active':
            selftest.show_active_testcases(xlfile)
        elif options.testcases == 'vsat':
            selftest.show_vsat_testcases(xlfile)
        elif options.run_active:
            selftest.run_active_testcases(xlfile)

        # ============ END MAIN BODY =============== #
    except Exception, e:
        indent = len(program_name) * " "
        sys.stderr.write(program_name + ": " + repr(e) + "\n")
        sys.stderr.write(indent + "  for help use --help")
        return 2


if __name__ == "__main__":
    if DEBUG:
        sys.argv.append("-h")
    if TESTRUN:
        import doctest
        doctest.testmod()
    if PROFILE:
        import cProfile
        import pstats
        profile_filename = 'test_profile.txt'
        cProfile.run('main()', profile_filename)
        statsfile = open("profile_stats.txt", "wb")
        p = pstats.Stats(profile_filename, stream=statsfile)
        stats = p.strip_dirs().sort_stats('cumulative')
        stats.print_stats()
        statsfile.close()
        sys.exit(0)
    sys.exit(main())
    
    